/**
 * Bibliotheque d'objets du Studio.
 *
 * Chaque entree est a la fois un modele 3D et une reference commerciale : elle
 * porte ses dimensions nominales en metres et, quand l'objet se loue ou se
 * vend, la fiche produit correspondante. Le catalogue de l'application est
 * genere depuis cette liste, si bien qu'un objet pose dans une scene arrive
 * toujours dans le devis avec sa designation, ses cotes et son prix.
 */
import type { EntityId, ProductMode } from '../../core/types';

export interface ObjectProduct {
  ref: string;
  name: string;
  brand: string;
  model: string;
  /** Categorie du catalogue (domaine « catalogue » de la taxonomie). */
  category: string;
  mode: ProductMode;
  unit: string;
  entity: EntityId;
  priceDay: number;
  priceSale: number;
  cost: number;
  weightKg: number;
  powerW: number;
  specs: Record<string, string>;
}

export interface ObjectDef {
  /** Cle du modele, stockee dans `SceneItem.model3d`. */
  id: string;
  label: string;
  /** Famille — libelle d'une categorie du domaine « objet3d ». */
  family: string;
  icon: string;
  /** Dimensions nominales : largeur, hauteur, profondeur, en metres. */
  size: [number, number, number];
  /** L'objet accepte des cotes libres. */
  resizable: boolean;
  /** Hauteur d'implantation par defaut, en metres (0 = pose au sol). */
  defaultY: number;
  /** L'objet projette un faisceau lumineux. */
  beam: boolean;
  /** Couleur par defaut du materiau principal ou du faisceau. */
  color?: string;
  hint?: string;
  /** L'objet represente une quantite (dalles, sieges) pilotee par `qty`. */
  countable?: boolean;
  /** Fiche produit : absente pour les objets de decor non factures. */
  product?: ObjectProduct;
}

type P = Partial<ObjectProduct>;

/** Fabrique une fiche produit avec les valeurs par defaut de la location. */
function prod(ref: string, name: string, category: string, priceDay: number, extra: P = {}): ObjectProduct {
  return {
    ref,
    name,
    brand: extra.brand ?? 'MSR',
    model: extra.model ?? '',
    category,
    mode: extra.mode ?? 'location',
    unit: extra.unit ?? 'unité',
    entity: extra.entity ?? 'msr',
    priceDay,
    priceSale: extra.priceSale ?? 0,
    cost: extra.cost ?? Math.round(priceDay * 18),
    weightKg: extra.weightKg ?? 0,
    powerW: extra.powerW ?? 0,
    specs: extra.specs ?? {},
  };
}

export const OBJECT_LIBRARY: ObjectDef[] = [
  /* ==================================================================== SON */
  {
    id: 'line-array',
    label: 'Élément de line array',
    family: 'Son',
    icon: '🔊',
    size: [0.72, 0.26, 0.44],
    resizable: false,
    defaultY: 6,
    beam: false,
    hint: 'À accrocher en grappe sous le pont',
    product: prod('KARA2', 'Line array L-Acoustics Kara II', 'Son — diffusion', 95, {
      brand: 'L-Acoustics',
      model: 'Kara II',
      unit: 'élément',
      cost: 6800,
      weightKg: 26,
      powerW: 400,
      specs: { SPL: '142 dB', Directivité: '110° x 10°', Bande: '55 Hz – 20 kHz' },
    }),
  },
  {
    id: 'sub',
    label: 'Caisson de basse',
    family: 'Son',
    icon: '🔊',
    size: [0.62, 0.6, 0.78],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('SB18', 'Caisson de basse L-Acoustics SB18', 'Son — diffusion', 85, {
      brand: 'L-Acoustics',
      model: 'SB18',
      cost: 5200,
      weightKg: 51,
      powerW: 700,
      specs: { SPL: '138 dB', Bande: '32 Hz – 100 Hz', Charge: 'Bass-reflex 18"' },
    }),
  },
  {
    id: 'top-speaker',
    label: 'Enceinte de façade',
    family: 'Son',
    icon: '🔈',
    size: [0.34, 0.52, 0.33],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('Y10P', 'Enceinte d&b audiotechnik Y10P', 'Son — diffusion', 55, {
      brand: 'd&b audiotechnik',
      model: 'Y10P',
      cost: 3100,
      weightKg: 19,
      powerW: 300,
      specs: { SPL: '137 dB', Directivité: '110° x 40°' },
    }),
  },
  {
    id: 'speaker-pole',
    label: 'Enceinte sur pied',
    family: 'Son',
    icon: '🔈',
    size: [0.4, 2.1, 0.4],
    resizable: false,
    defaultY: 0,
    beam: false,
    hint: 'Diffusion d’appoint, hauteur 2 m',
    product: prod('DBY7P', 'Enceinte d&b Y7P sur pied', 'Son — diffusion', 62, {
      brand: 'd&b audiotechnik',
      model: 'Y7P + pied K&M 21471',
      cost: 3400,
      weightKg: 24,
      powerW: 300,
      specs: { SPL: '138 dB', Hauteur: '1,6 à 2,2 m' },
    }),
  },
  {
    id: 'monitor',
    label: 'Retour de scène',
    family: 'Son',
    icon: '🎚️',
    size: [0.56, 0.34, 0.44],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('M4', 'Retour de scène d&b M4', 'Son — retours', 42, {
      brand: 'd&b audiotechnik',
      model: 'M4',
      cost: 2400,
      weightKg: 21,
      powerW: 250,
      specs: { SPL: '135 dB', Angle: '2 positions' },
    }),
  },
  {
    id: 'delay-tower',
    label: 'Tour de rappel',
    family: 'Son',
    icon: '🗼',
    size: [1.2, 5, 1.2],
    resizable: true,
    defaultY: 0,
    beam: false,
    hint: 'Diffusion différée pour les grandes jauges',
    product: prod('DELAY', 'Tour de rappel 3 boîtes + levage', 'Son — diffusion', 340, {
      brand: 'MSR',
      model: 'Delay Tower',
      unit: 'ensemble',
      cost: 9800,
      weightKg: 420,
      powerW: 900,
      specs: { Hauteur: '5 m', Charge: '250 kg', Inclus: 'Lest béton 400 kg' },
    }),
  },
  {
    id: 'console',
    label: 'Console & régie son',
    family: 'Son',
    icon: '🎛️',
    size: [1.5, 0.95, 0.8],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('CL5', 'Console numérique Yamaha CL5', 'Son — régie', 240, {
      brand: 'Yamaha',
      model: 'CL5',
      cost: 17500,
      weightKg: 38,
      powerW: 200,
      specs: { Entrées: '72 mono + 8 stéréo', Réseau: 'Dante 64x64' },
    }),
  },
  {
    id: 'console-compact',
    label: 'Console compacte',
    family: 'Son',
    icon: '🎛️',
    size: [1.1, 0.9, 0.7],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('M32', 'Console numérique Midas M32 Live', 'Son — régie', 120, {
      brand: 'Midas',
      model: 'M32 Live',
      cost: 4200,
      weightKg: 26,
      powerW: 150,
      specs: { Entrées: '32 préamplis', Réseau: 'AES50' },
    }),
  },
  {
    id: 'dj-booth',
    label: 'Régie DJ',
    family: 'Son',
    icon: '🎧',
    size: [1.7, 1.05, 0.62],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('CDJ3000', 'Régie DJ Pioneer 2x CDJ-3000 + DJM-A9', 'Son — DJ', 210, {
      brand: 'Pioneer DJ',
      model: 'CDJ-3000 / DJM-A9',
      unit: 'set',
      cost: 11200,
      weightKg: 32,
      powerW: 200,
      specs: { Écran: '9" tactile', Sorties: 'XLR + Digital' },
    }),
  },
  {
    id: 'amp-rack',
    label: 'Rack amplification',
    family: 'Son',
    icon: '🗄️',
    size: [0.6, 1.2, 0.75],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('LA12X', 'Rack amplification L-Acoustics LA12X', 'Son — régie', 165, {
      brand: 'L-Acoustics',
      model: 'LA12X',
      unit: 'rack',
      cost: 14500,
      weightKg: 62,
      powerW: 3200,
      specs: { Canaux: '4 x 3300 W', Alimentation: '32 A tri' },
    }),
  },
  {
    id: 'mic-stand',
    label: 'Pied de micro',
    family: 'Son',
    icon: '🎤',
    size: [0.32, 1.6, 0.32],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('K&M210', 'Pied de micro perche K&M 210/9', 'Son — micros', 6, {
      brand: 'König & Meyer',
      model: '210/9',
      cost: 95,
      weightKg: 3,
      specs: { Hauteur: '0,9 à 2,2 m' },
    }),
  },
  {
    id: 'hf-rack',
    label: 'Rack micros HF',
    family: 'Son',
    icon: '📡',
    size: [0.6, 1.1, 0.7],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('AD4Q', 'Micro HF Shure Axient AD4Q + 4 émetteurs', 'Son — micros', 180, {
      brand: 'Shure',
      model: 'Axient Digital AD4Q',
      unit: 'kit',
      cost: 9800,
      weightKg: 8,
      powerW: 60,
      specs: { Canaux: '4', Bande: '470 – 636 MHz' },
    }),
  },

  /* ================================================================ LUMIÈRE */
  {
    id: 'moving-head',
    label: 'Lyre spot',
    family: 'Lumière',
    icon: '💡',
    size: [0.34, 0.65, 0.34],
    resizable: false,
    defaultY: 6,
    beam: true,
    color: '#3987e5',
    product: prod('POINTE', 'Lyre Robe Pointe', 'Lumière — asservis', 68, {
      brand: 'Robe',
      model: 'Pointe',
      cost: 4900,
      weightKg: 23,
      powerW: 470,
      specs: { Source: 'Osram 280 W', Zoom: '2,5° – 20°', Prismes: '2' },
    }),
  },
  {
    id: 'moving-wash',
    label: 'Lyre wash',
    family: 'Lumière',
    icon: '💡',
    size: [0.36, 0.6, 0.36],
    resizable: false,
    defaultY: 6,
    beam: true,
    color: '#d95926',
    product: prod('MISTRAL', 'Lyre wash Ayrton Mistral-TC', 'Lumière — asservis', 74, {
      brand: 'Ayrton',
      model: 'Mistral-TC',
      cost: 5600,
      weightKg: 21,
      powerW: 350,
      specs: { Source: 'LED 300 W', Zoom: '7° – 55°', CRI: '> 90' },
    }),
  },
  {
    id: 'par-led',
    label: 'PAR LED',
    family: 'Lumière',
    icon: '🔦',
    size: [0.3, 0.34, 0.3],
    resizable: false,
    defaultY: 0.9,
    beam: true,
    color: '#9085e9',
    product: prod('COLORADO', 'PAR LED Chauvet COLORado 2 Solo', 'Lumière — statiques', 26, {
      brand: 'Chauvet Pro',
      model: 'COLORado 2 Solo',
      cost: 1150,
      weightKg: 9,
      powerW: 190,
      specs: { Source: 'RGBW 60 W', Zoom: '6° – 41°', IP: 'IP65' },
    }),
  },
  {
    id: 'blinder',
    label: 'Blinder',
    family: 'Lumière',
    icon: '🔆',
    size: [0.72, 0.4, 0.22],
    resizable: false,
    defaultY: 6,
    beam: true,
    color: '#ffd9a0',
    product: prod('BLINDER', 'Blinder Molefay 8 lite', 'Lumière — statiques', 34, {
      brand: 'Mole-Richardson',
      model: 'Molefay 8',
      cost: 980,
      weightKg: 12,
      powerW: 5200,
      specs: { Lampes: '8 x 650 W', Alimentation: 'DMX 2 circuits' },
    }),
  },
  {
    id: 'strobe',
    label: 'Stroboscope',
    family: 'Lumière',
    icon: '⚡',
    size: [0.5, 0.3, 0.2],
    resizable: false,
    defaultY: 5,
    beam: true,
    color: '#ffffff',
    product: prod('ATOMIC', 'Stroboscope Martin Atomic 3000 LED', 'Lumière — effets', 45, {
      brand: 'Martin',
      model: 'Atomic 3000 LED',
      cost: 2600,
      weightKg: 14,
      powerW: 850,
      specs: { Source: 'LED 1000 W', Effet: 'Strobe + eye-candy' },
    }),
  },
  {
    id: 'followspot',
    label: 'Poursuite',
    family: 'Lumière',
    icon: '🔦',
    size: [0.6, 1.5, 1.2],
    resizable: false,
    defaultY: 0,
    beam: true,
    color: '#fff3d0',
    product: prod('POURSUITE', 'Poursuite Robert Juliat Cyrano 2500 W', 'Lumière — asservis', 145, {
      brand: 'Robert Juliat',
      model: 'Cyrano 1014',
      cost: 8900,
      weightKg: 48,
      powerW: 2500,
      specs: { Portée: '30 m', Zoom: '3° – 8°' },
    }),
  },
  {
    id: 'uplight',
    label: 'Uplight décoratif',
    family: 'Lumière',
    icon: '🕯️',
    size: [0.22, 0.26, 0.22],
    resizable: false,
    defaultY: 0,
    beam: true,
    color: '#d55181',
    product: prod('UPLIGHT', 'Uplight LED sur batterie Astera AX3', 'Lumière — statiques', 18, {
      brand: 'Astera',
      model: 'AX3 LightDrop',
      cost: 420,
      weightKg: 1,
      powerW: 0,
      specs: { Autonomie: '20 h', Pilotage: 'CRMX sans fil', IP: 'IP65' },
    }),
  },
  {
    id: 'haze',
    label: 'Machine à brouillard',
    family: 'Lumière',
    icon: '🌫️',
    size: [0.5, 0.34, 0.34],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('MDGATMO', 'Machine à brouillard MDG Atmosphere APS', 'Lumière — effets', 90, {
      brand: 'MDG',
      model: 'Atmosphere APS',
      cost: 6400,
      weightKg: 18,
      powerW: 400,
      specs: { Fluide: 'Neutral', Autonomie: '10 h' },
    }),
  },
  {
    id: 'light-desk',
    label: 'Console lumière',
    family: 'Lumière',
    icon: '🎛️',
    size: [1.4, 0.95, 0.8],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('GRANDMA3', 'Console lumière grandMA3 light', 'Lumière — régie', 320, {
      brand: 'MA Lighting',
      model: 'grandMA3 light',
      cost: 42000,
      weightKg: 34,
      powerW: 250,
      specs: { Paramètres: '4 096', Écrans: '3 tactiles' },
    }),
  },
  {
    id: 'string-lights',
    label: 'Guirlande guinguette',
    family: 'Lumière',
    icon: '✨',
    size: [10, 0.2, 0.1],
    resizable: true,
    defaultY: 3.2,
    beam: false,
    color: '#ffcf8a',
    hint: 'Portée tendue entre deux points — la largeur donne la longueur',
    product: prod('GUINGUETTE', 'Guirlande guinguette 10 m — 20 douilles E27', 'Lumière — statiques', 14, {
      brand: 'Prolights',
      model: 'Festoon 10 m',
      unit: 'guirlande de 10 m',
      cost: 180,
      weightKg: 3,
      powerW: 80,
      specs: { Douilles: '20 x E27 LED', IP: 'IP44', Longueur: '10 m' },
    }),
  },
  {
    id: 'fairy-lights',
    label: 'Rideau lumineux',
    family: 'Lumière',
    icon: '🌟',
    size: [4, 3, 0.05],
    resizable: true,
    defaultY: 3,
    beam: false,
    color: '#ffe9c0',
    product: prod('RIDEAULED', 'Rideau lumineux LED 4 x 3 m', 'Lumière — statiques', 38, {
      brand: 'Showtec',
      model: 'Star Dream 4x3',
      unit: 'rideau',
      cost: 460,
      weightKg: 6,
      powerW: 60,
      specs: { Points: '576 LED', Effet: 'Scintillement DMX' },
    }),
  },
  {
    id: 'neon-sign',
    label: 'Enseigne lumineuse',
    family: 'Lumière',
    icon: '🔤',
    size: [2, 0.6, 0.1],
    resizable: true,
    defaultY: 1.6,
    beam: false,
    color: '#e66767',
    product: prod('NEON', 'Enseigne néon LED personnalisée', 'Lumière — statiques', 45, {
      brand: 'Owlaris',
      model: 'Néon sur mesure',
      entity: 'owlaris',
      unit: 'enseigne',
      cost: 520,
      weightKg: 8,
      powerW: 40,
      specs: { Support: 'Plexiglas', Fixation: 'Suspendue ou murale' },
    }),
  },
  {
    id: 'mirror-ball',
    label: 'Boule à facettes',
    family: 'Lumière',
    icon: '🪩',
    size: [0.5, 0.5, 0.5],
    resizable: true,
    defaultY: 3.5,
    beam: false,
    product: prod('BOULE50', 'Boule à facettes 50 cm + moteur', 'Lumière — effets', 28, {
      brand: 'Eurolite',
      model: 'Mirror Ball 50',
      unit: 'ensemble',
      cost: 240,
      weightKg: 9,
      powerW: 15,
      specs: { Diamètre: '50 cm', Moteur: '1,5 tr/min' },
    }),
  },

  /* ================================================================== VIDÉO */
  {
    id: 'led-wall',
    label: 'Mur LED',
    family: 'Vidéo',
    icon: '🟥',
    size: [6, 3, 0.12],
    resizable: true,
    defaultY: 1.5,
    beam: false,
    countable: true,
    hint: 'Dalles de 0,5 m — la quantité pilote la surface',
    product: prod('ROECB5', 'Dalle LED ROE Carbon CB5 (0,5 x 0,5 m)', 'Vidéo — LED', 38, {
      brand: 'ROE Visual',
      model: 'Carbon CB5',
      unit: 'dalle',
      cost: 1450,
      weightKg: 8,
      powerW: 120,
      specs: { Pitch: '5,77 mm', Luminosité: '4 500 nits', Indoor: 'IP54' },
    }),
  },
  {
    id: 'projection-screen',
    label: 'Écran de projection',
    family: 'Vidéo',
    icon: '⬜',
    size: [5, 3, 0.08],
    resizable: true,
    defaultY: 1.8,
    beam: false,
    product: prod('ECRAN43', 'Écran de projection sur cadre 5 x 3 m', 'Vidéo — projection', 120, {
      brand: 'Adeo Screen',
      model: 'FrameScreen 500',
      unit: 'écran',
      cost: 2200,
      weightKg: 46,
      specs: { Toile: 'Blanc mat gain 1.0', Format: '16:9' },
    }),
  },
  {
    id: 'projector',
    label: 'Vidéoprojecteur',
    family: 'Vidéo',
    icon: '📽️',
    size: [0.6, 0.28, 0.7],
    resizable: false,
    defaultY: 4,
    beam: true,
    color: '#cfe2ff',
    product: prod('PJ10K', 'Vidéoprojecteur laser 10 000 lm Epson EB-PU1008', 'Vidéo — projection', 280, {
      brand: 'Epson',
      model: 'EB-PU1008B',
      cost: 12500,
      weightKg: 23,
      powerW: 750,
      specs: { Luminosité: '10 000 lm', Résolution: 'WUXGA', Optique: 'Interchangeable' },
    }),
  },
  {
    id: 'tv-screen',
    label: 'Écran plat sur pied',
    family: 'Vidéo',
    icon: '📺',
    size: [1.3, 1.9, 0.5],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('TV55', 'Écran 55" sur pied mobile', 'Vidéo — projection', 85, {
      brand: 'Samsung',
      model: 'QM55B + pied Vogel',
      unit: 'ensemble',
      cost: 1800,
      weightKg: 42,
      powerW: 180,
      specs: { Diagonale: '139 cm', Entrées: 'HDMI x3' },
    }),
  },
  {
    id: 'camera',
    label: 'Caméra sur pied',
    family: 'Vidéo',
    icon: '🎥',
    size: [0.6, 1.55, 0.7],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('CAMPTZ', 'Caméra PTZ full HD + trépied', 'Vidéo — projection', 130, {
      brand: 'Panasonic',
      model: 'AW-UE80',
      unit: 'ensemble',
      cost: 5400,
      weightKg: 12,
      powerW: 60,
      specs: { Zoom: 'x24', Sortie: 'SDI / NDI' },
    }),
  },

  /* ==================================================== STRUCTURE & SCÈNE */
  {
    id: 'truss',
    label: 'Poutre de structure',
    family: 'Structure & scène',
    icon: '🏗️',
    size: [3, 0.29, 0.29],
    resizable: true,
    defaultY: 6,
    beam: false,
    hint: 'La largeur donne la longueur de poutre',
    product: prod('H30V3', 'Structure Prolyte H30V — poutre 3 m', 'Structure', 18, {
      brand: 'Prolyte',
      model: 'H30V-L300',
      unit: 'poutre',
      cost: 420,
      weightKg: 14,
      specs: { Section: '290 mm', Charge: '1 100 kg à 6 m' },
    }),
  },
  {
    id: 'truss-tower',
    label: 'Tour de levage',
    family: 'Structure & scène',
    icon: '🗼',
    size: [1.1, 6, 1.1],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('MT1', 'Tour de levage Milos MT1 (6 m)', 'Structure', 55, {
      brand: 'Milos',
      model: 'MT1',
      cost: 2100,
      weightKg: 78,
      specs: { Hauteur: '6,2 m', Charge: '250 kg' },
    }),
  },
  {
    id: 'truss-arch',
    label: 'Arche de structure',
    family: 'Structure & scène',
    icon: '🌉',
    size: [8, 5, 0.4],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('ARCHE', 'Arche de structure 8 x 5 m montée', 'Structure', 210, {
      brand: 'Prolyte',
      model: 'H30V arche',
      unit: 'ensemble',
      cost: 3600,
      weightKg: 190,
      specs: { Portée: '8 m', Hauteur: '5 m', Lest: '2 x 200 kg' },
    }),
  },
  {
    id: 'stage-deck',
    label: 'Praticable',
    family: 'Structure & scène',
    icon: '🟫',
    size: [2, 0.8, 1],
    resizable: true,
    defaultY: 0,
    beam: false,
    hint: 'La hauteur règle les pieds',
    product: prod('NIVTEC', 'Praticable Nivtec 2 x 1 m', 'Structure', 16, {
      brand: 'Nivtec',
      model: '200x100',
      unit: 'praticable',
      cost: 380,
      weightKg: 27,
      specs: { Charge: '750 kg/m²', Hauteurs: '20 à 100 cm' },
    }),
  },
  {
    id: 'stage-stairs',
    label: 'Escalier de scène',
    family: 'Structure & scène',
    icon: '🪜',
    size: [1.2, 0.8, 1.2],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('ESCALIER', 'Escalier de scène 4 marches + main courante', 'Structure', 34, {
      brand: 'Nivtec',
      model: 'Escalier 100',
      unit: 'escalier',
      cost: 620,
      weightKg: 38,
      specs: { Marches: '4', Largeur: '1 m' },
    }),
  },
  {
    id: 'stage-rail',
    label: 'Garde-corps',
    family: 'Structure & scène',
    icon: '🚧',
    size: [2, 1, 0.08],
    resizable: true,
    defaultY: 0.8,
    beam: false,
    product: prod('GARDECORPS', 'Garde-corps de scène 2 m', 'Structure', 9, {
      brand: 'Nivtec',
      model: 'GC200',
      unit: 'élément de 2 m',
      cost: 190,
      weightKg: 11,
      specs: { Hauteur: '1 m', Norme: 'EN 13814' },
    }),
  },
  {
    id: 'stage-skirt',
    label: 'Jupe de scène',
    family: 'Structure & scène',
    icon: '🎭',
    size: [4, 0.8, 0.05],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('JUPE', 'Jupe de scène velours noir', 'Structure', 7, {
      brand: 'Showtex',
      model: 'Velours M1',
      unit: 'mètre linéaire',
      cost: 60,
      weightKg: 2,
      specs: { Classement: 'M1', Fixation: 'Velcro' },
    }),
  },
  {
    id: 'pipe-drape',
    label: 'Tenture sur portique',
    family: 'Structure & scène',
    icon: '🎭',
    size: [4, 3, 0.3],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('PIPEDRAPE', 'Tenture sur portique 4 x 3 m', 'Structure', 42, {
      brand: 'Wentex',
      model: 'Pipe & Drape',
      unit: 'travée',
      cost: 480,
      weightKg: 34,
      specs: { Tissu: 'Molleton M1', Hauteur: 'Réglable 2 à 4 m' },
    }),
  },
  {
    id: 'dance-floor',
    label: 'Piste de danse',
    family: 'Structure & scène',
    icon: '🕺',
    size: [6, 0.06, 6],
    resizable: true,
    defaultY: 0,
    beam: false,
    hint: 'Dalles clipsables, surface libre',
    product: prod('PISTE', 'Piste de danse blanche/noire — la dalle 1 x 1 m', 'Structure', 11, {
      brand: 'Exposhow',
      model: 'Dancefloor 100',
      unit: 'm²',
      cost: 145,
      weightKg: 14,
      specs: { Finition: 'Damier ou uni', Épaisseur: '6 cm avec plots' },
    }),
  },

  /* ================================================ MOBILIER & RÉCEPTION */
  {
    id: 'table-brasserie',
    label: 'Table brasserie',
    family: 'Mobilier & réception',
    icon: '🍺',
    size: [2.2, 0.76, 0.7],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('TBRASS', 'Table brasserie pliante 220 x 70 cm', 'Mobilier', 6, {
      brand: 'Zown',
      model: 'Bierzelt 220',
      cost: 78,
      weightKg: 17,
      specs: { Places: '8 à 10', Plateau: 'Bois verni', Pliage: 'Pieds rabattables' },
    }),
  },
  {
    id: 'banc-brasserie',
    label: 'Banc brasserie',
    family: 'Mobilier & réception',
    icon: '🪵',
    size: [2.2, 0.47, 0.25],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('BBRASS', 'Banc brasserie pliant 220 x 25 cm', 'Mobilier', 3.5, {
      brand: 'Zown',
      model: 'Bierzelt Bank',
      cost: 44,
      weightKg: 11,
      specs: { Places: '4', Plateau: 'Bois verni' },
    }),
  },
  {
    id: 'table-round',
    label: 'Table ronde nappée',
    family: 'Mobilier & réception',
    icon: '🍽️',
    size: [1.8, 0.76, 1.8],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('TRONDE180', 'Table ronde Ø 180 cm — 10 couverts', 'Mobilier', 12, {
      brand: 'Zown',
      model: 'Round 180',
      cost: 165,
      weightKg: 24,
      specs: { Places: '10', Nappe: 'En option 4 €' },
    }),
  },
  {
    id: 'table-rect',
    label: 'Table rectangulaire',
    family: 'Mobilier & réception',
    icon: '🪑',
    size: [1.8, 0.75, 0.8],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('TRECT180', 'Table rectangulaire 180 x 80 cm', 'Mobilier', 8, {
      brand: 'Zown',
      model: 'Rect 180',
      cost: 110,
      weightKg: 18,
      specs: { Places: '8', Plateau: 'Polypropylène' },
    }),
  },
  {
    id: 'cocktail-table',
    label: 'Mange-debout',
    family: 'Mobilier & réception',
    icon: '🥂',
    size: [0.8, 1.1, 0.8],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('MANGEDEBOUT', 'Mange-debout Ø 80 cm + housse', 'Mobilier', 9, {
      brand: 'Zown',
      model: 'Cocktail 80',
      unit: 'ensemble',
      cost: 120,
      weightKg: 13,
      specs: { Hauteur: '110 cm', Housse: 'Blanche ou noire' },
    }),
  },
  {
    id: 'chair',
    label: 'Chaise pliante',
    family: 'Mobilier & réception',
    icon: '🪑',
    size: [0.46, 0.9, 0.5],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('CHAISE', 'Chaise pliante coque grise', 'Mobilier', 2, {
      brand: 'Zown',
      model: 'Alex',
      cost: 26,
      weightKg: 4,
      specs: { Empilable: 'Oui', Extérieur: 'Oui' },
    }),
  },
  {
    id: 'chaise-napoleon',
    label: 'Chaise Napoléon',
    family: 'Mobilier & réception',
    icon: '👑',
    size: [0.42, 0.94, 0.45],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('NAPOLEON', 'Chaise Napoléon III transparente + galette', 'Mobilier', 3.5, {
      brand: 'Vision',
      model: 'Napoléon PC',
      cost: 42,
      weightKg: 3,
      specs: { Assise: 'Galette blanche ou noire', Usage: 'Cérémonie, dîner' },
    }),
  },
  {
    id: 'bench',
    label: 'Banc bois',
    family: 'Mobilier & réception',
    icon: '🪵',
    size: [1.8, 0.45, 0.4],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('BANCBOIS', 'Banc bois massif 180 cm', 'Mobilier', 5, {
      brand: 'MSR',
      model: 'Banc chêne',
      cost: 95,
      weightKg: 16,
      specs: { Places: '3' },
    }),
  },
  {
    id: 'lounge-sofa',
    label: 'Canapé lounge',
    family: 'Mobilier & réception',
    icon: '🛋️',
    size: [1.9, 0.75, 0.85],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('CANAPE', 'Canapé lounge 3 places simili cuir', 'Mobilier', 42, {
      brand: 'Vondom',
      model: 'Lounge 3P',
      cost: 620,
      weightKg: 34,
      specs: { Places: '3', Revêtement: 'Simili blanc ou noir' },
    }),
  },
  {
    id: 'armchair',
    label: 'Fauteuil lounge',
    family: 'Mobilier & réception',
    icon: '💺',
    size: [0.85, 0.75, 0.85],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('FAUTEUIL', 'Fauteuil lounge simili cuir', 'Mobilier', 22, {
      brand: 'Vondom',
      model: 'Lounge 1P',
      cost: 290,
      weightKg: 18,
      specs: { Places: '1' },
    }),
  },
  {
    id: 'transat',
    label: 'Transat',
    family: 'Mobilier & réception',
    icon: '🏖️',
    size: [0.65, 0.85, 1.5],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('TRANSAT', 'Transat bois et toile', 'Mobilier', 7, {
      brand: 'Fermob',
      model: 'Bistro chaise longue',
      cost: 95,
      weightKg: 6,
      specs: { Matériau: 'Hêtre + toile coton' },
    }),
  },
  {
    id: 'buffet',
    label: 'Buffet nappé',
    family: 'Mobilier & réception',
    icon: '🍱',
    size: [2.4, 0.9, 0.8],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('BUFFET', 'Buffet nappé 240 cm + 3 bacs inox', 'Mobilier', 26, {
      brand: 'MSR',
      model: 'Buffet 240',
      unit: 'ensemble',
      cost: 340,
      weightKg: 28,
      specs: { Longueur: '2,4 m', Inclus: 'Nappe et jupe' },
    }),
  },
  {
    id: 'lectern',
    label: 'Pupitre orateur',
    family: 'Mobilier & réception',
    icon: '🎙️',
    size: [0.66, 1.2, 0.45],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('PUPITRE', 'Pupitre orateur plexiglas + micro col de cygne', 'Mobilier', 48, {
      brand: 'Owlaris',
      model: 'Pupitre PMMA',
      entity: 'owlaris',
      unit: 'ensemble',
      cost: 780,
      weightKg: 22,
      powerW: 20,
      specs: { Éclairage: 'LED lutrin', Micro: 'Col de cygne inclus' },
    }),
  },
  {
    id: 'seating-block',
    label: 'Bloc de sièges',
    family: 'Mobilier & réception',
    icon: '👥',
    size: [8, 0.9, 6],
    resizable: true,
    defaultY: 0,
    beam: false,
    countable: true,
    hint: 'La quantité fixe le nombre de places',
    product: prod('CHAISE', 'Chaise pliante coque grise', 'Mobilier', 2, {
      brand: 'Zown',
      model: 'Alex',
      unit: 'place',
      cost: 26,
      weightKg: 4,
      specs: { Empilable: 'Oui' },
    }),
  },
  {
    id: 'coat-rack',
    label: 'Vestiaire',
    family: 'Mobilier & réception',
    icon: '🧥',
    size: [1.8, 1.7, 0.6],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('VESTIAIRE', 'Portant vestiaire 180 cm + 50 cintres', 'Mobilier', 16, {
      brand: 'MSR',
      model: 'Portant pro',
      unit: 'ensemble',
      cost: 145,
      weightKg: 14,
      specs: { Capacité: '50 manteaux' },
    }),
  },
  {
    id: 'bin',
    label: 'Poubelle de tri',
    family: 'Mobilier & réception',
    icon: '🗑️',
    size: [0.5, 0.9, 0.5],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('POUBELLE', 'Poubelle de tri 110 L sur support', 'Mobilier', 5, {
      brand: 'Rossignol',
      model: 'Collecmur 110',
      cost: 68,
      weightKg: 7,
      specs: { Volume: '110 L', Sacs: 'Fournis' },
    }),
  },

  /* =================================================== BAR & RESTAURATION */
  {
    id: 'bar',
    label: 'Bar comptoir',
    family: 'Bar & restauration',
    icon: '🍸',
    size: [2, 1.15, 0.7],
    resizable: true,
    defaultY: 0,
    beam: false,
    hint: 'Modules de 1 m — la largeur donne le linéaire',
    product: prod('BARMOD', 'Bar modulaire bois — module 1 m', 'Bar & restauration', 24, {
      brand: 'MSR',
      model: 'Bar Guinguette',
      unit: 'module de 1 m',
      cost: 340,
      weightKg: 32,
      specs: { Plan: 'Chêne massif', Hauteur: '1,15 m', Habillage: 'Face avant personnalisable' },
    }),
  },
  {
    id: 'back-bar',
    label: 'Arrière-bar réfrigéré',
    family: 'Bar & restauration',
    icon: '🍾',
    size: [2.4, 1.9, 0.5],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('ARRIEREBAR', 'Arrière-bar réfrigéré 3 portes vitrées', 'Bar & restauration', 68, {
      brand: 'Polar',
      model: 'GL012',
      cost: 1450,
      weightKg: 120,
      powerW: 350,
      specs: { Volume: '368 L', Température: '+1 à +10 °C' },
    }),
  },
  {
    id: 'pompe-biere',
    label: 'Pompe à bière',
    family: 'Bar & restauration',
    icon: '🍺',
    size: [0.4, 0.65, 0.45],
    resizable: false,
    defaultY: 1.15,
    beam: false,
    hint: 'À poser sur le comptoir',
    product: prod('TIREUSE2', 'Tireuse à bière 2 becs Lindr PYGMY 25/K', 'Bar & restauration', 75, {
      brand: 'Lindr',
      model: 'PYGMY 25/K Profi',
      unit: 'tireuse',
      cost: 980,
      weightKg: 26,
      powerW: 400,
      specs: { Débit: '25 L/h', Becs: '2', Refroidissement: 'Circuit sec' },
    }),
  },
  {
    id: 'fut-biere',
    label: 'Fût de bière',
    family: 'Bar & restauration',
    icon: '🛢️',
    size: [0.4, 0.6, 0.4],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('FUT30', 'Fût de bière 30 L (consigne incluse)', 'Bar & restauration', 0, {
      brand: 'Divers',
      model: 'Keg 30 L',
      mode: 'vente',
      unit: 'fût',
      priceSale: 145,
      cost: 92,
      weightKg: 38,
      specs: { Volume: '30 L', Rendement: '≈ 120 pintes' },
    }),
  },
  {
    id: 'frigo-boissons',
    label: 'Frigo à boissons',
    family: 'Bar & restauration',
    icon: '🧊',
    size: [0.6, 1.9, 0.65],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('FRIGO600', 'Armoire réfrigérée vitrée 600 L', 'Bar & restauration', 45, {
      brand: 'Polar',
      model: 'CD088',
      cost: 890,
      weightKg: 95,
      powerW: 300,
      specs: { Volume: '600 L', Température: '+2 à +8 °C', Éclairage: 'LED' },
    }),
  },
  {
    id: 'congelateur',
    label: 'Congélateur coffre',
    family: 'Bar & restauration',
    icon: '❄️',
    size: [1.1, 0.9, 0.7],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('CONGEL300', 'Congélateur coffre 300 L', 'Bar & restauration', 32, {
      brand: 'Polar',
      model: 'CM431',
      cost: 620,
      weightKg: 62,
      powerW: 250,
      specs: { Volume: '300 L', Température: '−18 °C' },
    }),
  },
  {
    id: 'chambre-froide',
    label: 'Chambre froide',
    family: 'Bar & restauration',
    icon: '🚪',
    size: [2.4, 2.2, 2.4],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('CFROIDE6', 'Chambre froide démontable 6 m³ positive', 'Bar & restauration', 180, {
      brand: 'Dagard',
      model: 'Modulaire 6 m³',
      unit: 'ensemble',
      cost: 4800,
      weightKg: 380,
      powerW: 1200,
      specs: { Volume: '6 m³', Température: '0 à +6 °C', Montage: 'Panneaux clipsés' },
    }),
  },
  {
    id: 'machine-glacons',
    label: 'Machine à glaçons',
    family: 'Bar & restauration',
    icon: '🧊',
    size: [0.6, 0.9, 0.6],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('GLACONS60', 'Machine à glaçons 60 kg/24 h', 'Bar & restauration', 58, {
      brand: 'Brema',
      model: 'CB640',
      cost: 1650,
      weightKg: 58,
      powerW: 700,
      specs: { Production: '60 kg/24 h', Réserve: '25 kg', Eau: 'Raccordement 3/4"' },
    }),
  },
  {
    id: 'plancha',
    label: 'Plancha gaz',
    family: 'Bar & restauration',
    icon: '🍳',
    size: [1.2, 0.95, 0.6],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('PLANCHA', 'Plancha gaz 2 feux sur chariot', 'Bar & restauration', 55, {
      brand: 'Forge Adour',
      model: 'Prestige 900',
      unit: 'ensemble',
      cost: 780,
      weightKg: 48,
      specs: { Surface: '90 x 45 cm', Énergie: 'Gaz propane', Inclus: 'Détendeur' },
    }),
  },
  {
    id: 'friteuse',
    label: 'Friteuse',
    family: 'Bar & restauration',
    icon: '🍟',
    size: [0.6, 1.1, 0.6],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('FRITEUSE', 'Friteuse électrique 2 x 8 L sur coffre', 'Bar & restauration', 42, {
      brand: 'Bartscher',
      model: 'Imbiss II 2x8',
      cost: 690,
      weightKg: 34,
      powerW: 6000,
      specs: { Cuves: '2 x 8 L', Alimentation: '400 V tri' },
    }),
  },
  {
    id: 'four-pizza',
    label: 'Four à pizza mobile',
    family: 'Bar & restauration',
    icon: '🍕',
    size: [1.1, 1.6, 1.3],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('FOURPIZZA', 'Four à pizza à bois mobile sur roues', 'Bar & restauration', 145, {
      brand: 'Alfa Forni',
      model: 'Zeno mobile',
      unit: 'ensemble',
      cost: 3200,
      weightKg: 210,
      specs: { Capacité: '4 pizzas', Énergie: 'Bois ou gaz', Température: '450 °C' },
    }),
  },
  {
    id: 'percolateur',
    label: 'Percolateur',
    family: 'Bar & restauration',
    icon: '☕',
    size: [0.35, 0.6, 0.35],
    resizable: false,
    defaultY: 1.15,
    beam: false,
    product: prod('PERCO100', 'Percolateur 100 tasses', 'Bar & restauration', 24, {
      brand: 'Animo',
      model: 'ComBi-line 15',
      cost: 420,
      weightKg: 9,
      powerW: 2200,
      specs: { Capacité: '15 L / 100 tasses', Temps: '35 min' },
    }),
  },
  {
    id: 'machine-granite',
    label: 'Machine à granité',
    family: 'Bar & restauration',
    icon: '🥤',
    size: [0.55, 0.85, 0.5],
    resizable: false,
    defaultY: 1.15,
    beam: false,
    product: prod('GRANITE3', 'Machine à granité 3 x 12 L', 'Bar & restauration', 68, {
      brand: 'Ugolini',
      model: 'Arctic Compact 3',
      cost: 2400,
      weightKg: 42,
      powerW: 900,
      specs: { Bols: '3 x 12 L', Éclairage: 'LED' },
    }),
  },
  {
    id: 'plonge',
    label: 'Plonge inox',
    family: 'Bar & restauration',
    icon: '🚰',
    size: [1.4, 0.95, 0.7],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('PLONGE2', 'Plonge inox 2 bacs + égouttoir', 'Bar & restauration', 28, {
      brand: 'Bartscher',
      model: 'Plonge 1400',
      cost: 520,
      weightKg: 46,
      specs: { Bacs: '2 x 40 L', Raccordement: 'Eau + évacuation' },
    }),
  },
  {
    id: 'table-inox',
    label: 'Table de travail inox',
    family: 'Bar & restauration',
    icon: '🔪',
    size: [1.6, 0.9, 0.7],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('TABLEINOX', 'Table de travail inox 160 cm avec étagère', 'Bar & restauration', 14, {
      brand: 'Bartscher',
      model: 'Inox 1600',
      cost: 240,
      weightKg: 28,
      specs: { Plateau: 'Inox 304', Étagère: 'Basse' },
    }),
  },
  {
    id: 'caisse',
    label: 'Poste d’encaissement',
    family: 'Bar & restauration',
    icon: '💳',
    size: [0.5, 0.4, 0.4],
    resizable: false,
    defaultY: 1.15,
    beam: false,
    product: prod('CAISSE', 'Caisse tactile + TPE sans contact', 'Bar & restauration', 38, {
      brand: 'SumUp',
      model: 'Point of Sale',
      unit: 'ensemble',
      cost: 690,
      weightKg: 5,
      powerW: 60,
      specs: { Paiement: 'CB sans contact', Réseau: '4G incluse' },
    }),
  },
  {
    id: 'foodtruck',
    label: 'Remorque food-truck',
    family: 'Bar & restauration',
    icon: '🚚',
    size: [2.2, 2.6, 4.5],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('FOODTRUCK', 'Remorque food-truck équipée 4,5 m', 'Bar & restauration', 420, {
      brand: 'MSR',
      model: 'Remorque snack',
      unit: 'remorque',
      cost: 24000,
      weightKg: 1200,
      powerW: 8000,
      specs: { Équipement: 'Plancha, friteuse, frigo, plonge', Alimentation: '32 A' },
    }),
  },

  /* ======================================================= TENTES & ABRIS */
  {
    id: 'tente-stretch',
    label: 'Tente stretch',
    family: 'Tentes & abris',
    icon: '⛺',
    size: [10, 4.5, 15],
    resizable: true,
    defaultY: 0,
    beam: false,
    hint: 'Toile tendue sur mâts — forme libre, aucun pied central',
    product: prod('STRETCH150', 'Tente stretch 10 x 15 m montée', 'Tentes & abris', 620, {
      brand: 'Stretch Tent Pro',
      model: 'ST-150',
      unit: 'tente',
      cost: 12500,
      weightKg: 180,
      specs: {
        'Surface couverte': '150 m²',
        'Hauteur sous mât': '4,5 m',
        Toile: 'Polyester enduit M2',
        Vent: 'Jusqu’à 60 km/h ancrée',
        Montage: '4 h à 4 personnes',
      },
    }),
  },
  {
    id: 'tonnelle',
    label: 'Tonnelle pliante 3 x 3',
    family: 'Tentes & abris',
    icon: '⛱️',
    size: [3, 3.1, 3],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('VITABRI33', 'Tonnelle pliante pro Vitabri V3 — 3 x 3 m', 'Tentes & abris', 68, {
      brand: 'Vitabri',
      model: 'V3 3x3',
      unit: 'tonnelle',
      cost: 1150,
      weightKg: 42,
      specs: {
        'Surface couverte': '9 m²',
        Structure: 'Aluminium 50 mm',
        Toile: 'Polyester 300 g M2',
        Montage: '2 personnes, 5 min',
      },
    }),
  },
  {
    id: 'tonnelle-48',
    label: 'Tonnelle pliante 4 x 8',
    family: 'Tentes & abris',
    icon: '⛱️',
    size: [4, 3.2, 8],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('VITABRI48', 'Tonnelle pliante pro Vitabri V3 — 4 x 8 m', 'Tentes & abris', 145, {
      brand: 'Vitabri',
      model: 'V3 4x8',
      unit: 'tonnelle',
      cost: 2600,
      weightKg: 88,
      specs: { 'Surface couverte': '32 m²', Structure: 'Aluminium renforcé', Toile: 'Polyester 300 g M2' },
    }),
  },
  {
    id: 'barnum',
    label: 'Barnum',
    family: 'Tentes & abris',
    icon: '🏕️',
    size: [5, 3.2, 10],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('BARNUM510', 'Barnum 5 x 10 m avec parois', 'Tentes & abris', 210, {
      brand: 'Intent24',
      model: 'Barnum PVC 5x10',
      unit: 'barnum',
      cost: 3400,
      weightKg: 210,
      specs: { 'Surface couverte': '50 m²', Parois: '4 amovibles', Toile: 'PVC 500 g M2' },
    }),
  },
  {
    id: 'chapiteau',
    label: 'Chapiteau',
    family: 'Tentes & abris',
    icon: '🎪',
    size: [15, 5.5, 20],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('CHAPITEAU', 'Chapiteau 15 x 20 m monté avec plancher', 'Tentes & abris', 1450, {
      brand: 'Losberger',
      model: 'Ambassador 15 m',
      unit: 'chapiteau',
      cost: 46000,
      weightKg: 3800,
      specs: {
        'Surface couverte': '300 m²',
        'Hauteur sous ferme': '5,5 m',
        Capacité: '300 assis, 500 debout',
        Montage: '2 jours',
      },
    }),
  },
  {
    id: 'pagode',
    label: 'Tente pagode',
    family: 'Tentes & abris',
    icon: '⛺',
    size: [5, 4.2, 5],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('PAGODE5', 'Tente pagode 5 x 5 m', 'Tentes & abris', 240, {
      brand: 'Röder',
      model: 'Pagode 5x5',
      unit: 'tente',
      cost: 4200,
      weightKg: 260,
      specs: { 'Surface couverte': '25 m²', 'Hauteur sous barre': '2,6 m', Faîtage: '4,2 m' },
    }),
  },
  {
    id: 'parasol',
    label: 'Parasol',
    family: 'Tentes & abris',
    icon: '🏖️',
    size: [3, 2.6, 3],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('PARASOL3', 'Parasol déporté 3 m + socle lesté', 'Tentes & abris', 22, {
      brand: 'Fermob',
      model: 'Shadoo 300',
      unit: 'ensemble',
      cost: 380,
      weightKg: 48,
      specs: { Diamètre: '3 m', Socle: 'Dalles 60 kg' },
    }),
  },
  {
    id: 'auvent-bar',
    label: 'Auvent de bar',
    family: 'Tentes & abris',
    icon: '🏪',
    size: [4, 2.8, 2],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('AUVENT', 'Auvent de bar 4 x 2 m', 'Tentes & abris', 62, {
      brand: 'MSR',
      model: 'Auvent alu',
      unit: 'auvent',
      cost: 890,
      weightKg: 56,
      specs: { 'Surface couverte': '8 m²', Toile: 'PVC rayé' },
    }),
  },

  /* ==================================================== SANITAIRES & CONFORT */
  {
    id: 'wc-mobile',
    label: 'Cabine WC autonome',
    family: 'Sanitaires & confort',
    icon: '🚻',
    size: [1.15, 2.3, 1.15],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('WCAUTO', 'Cabine WC autonome (fosse 250 L)', 'Sanitaires & confort', 95, {
      brand: 'Sebach',
      model: 'Cabine standard',
      unit: 'cabine',
      cost: 900,
      weightKg: 78,
      specs: { Fosse: '250 L', Capacité: '≈ 250 passages', Livraison: 'Incluse dans le rayon' },
    }),
  },
  {
    id: 'wc-pmr',
    label: 'Cabine WC PMR',
    family: 'Sanitaires & confort',
    icon: '♿',
    size: [1.6, 2.3, 1.6],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('WCPMR', 'Cabine WC PMR accessible', 'Sanitaires & confort', 165, {
      brand: 'Sebach',
      model: 'Cabine PMR',
      unit: 'cabine',
      cost: 1600,
      weightKg: 110,
      specs: { Accès: 'Rampe intégrée', Norme: 'Accessibilité ERP' },
    }),
  },
  {
    id: 'bloc-lavabo',
    label: 'Bloc lavabo',
    family: 'Sanitaires & confort',
    icon: '🚿',
    size: [1.4, 1.3, 0.7],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('LAVABO4', 'Bloc lavabo 4 postes autonome', 'Sanitaires & confort', 78, {
      brand: 'Sebach',
      model: 'Lave-mains 4',
      unit: 'bloc',
      cost: 820,
      weightKg: 62,
      specs: { Postes: '4', Réservoir: '100 L', Savon: 'Distributeurs inclus' },
    }),
  },
  {
    id: 'parasol-chauffant',
    label: 'Parasol chauffant',
    family: 'Sanitaires & confort',
    icon: '🔥',
    size: [0.8, 2.2, 0.8],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('CHAUFFANT', 'Parasol chauffant gaz 13 kW', 'Sanitaires & confort', 32, {
      brand: 'Favex',
      model: 'Pyramide inox',
      unit: 'parasol',
      cost: 420,
      weightKg: 32,
      specs: { Puissance: '13 kW', Rayon: '≈ 20 m²', Gaz: 'Bouteille 13 kg non fournie' },
    }),
  },
  {
    id: 'brasero',
    label: 'Brasero',
    family: 'Sanitaires & confort',
    icon: '🔥',
    size: [0.8, 0.6, 0.8],
    resizable: false,
    defaultY: 0,
    beam: false,
    color: '#ff8a3d',
    product: prod('BRASERO', 'Brasero acier corten Ø 80 cm', 'Sanitaires & confort', 24, {
      brand: 'Höfats',
      model: 'Corten 80',
      unit: 'brasero',
      cost: 340,
      weightKg: 28,
      specs: { Diamètre: '80 cm', Combustible: 'Bûches' },
    }),
  },
  {
    id: 'chauffage-air-pulse',
    label: 'Chauffage air pulsé',
    family: 'Sanitaires & confort',
    icon: '♨️',
    size: [1.2, 1.1, 0.8],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('AIRPULSE', 'Chauffage air pulsé fioul 50 kW + gaine', 'Sanitaires & confort', 130, {
      brand: 'Master',
      model: 'BV 470',
      unit: 'ensemble',
      cost: 2400,
      weightKg: 92,
      powerW: 900,
      specs: { Puissance: '50 kW', Volume: 'Jusqu’à 1 200 m³', Gaine: '10 m Ø 60 cm' },
    }),
  },

  /* ===================================================== DÉCOR & EXTÉRIEUR */
  {
    id: 'arche-florale',
    label: 'Arche florale',
    family: 'Décor & extérieur',
    icon: '💐',
    size: [2.4, 2.6, 0.6],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('ARCHEFLO', 'Arche florale décorée', 'Décor', 180, {
      brand: 'Marée Sonore',
      model: 'Arche cérémonie',
      entity: 'maree-sonore',
      unit: 'arche',
      cost: 420,
      weightKg: 24,
      specs: { Structure: 'Métal noir', Fleuri: 'Composition saisonnière incluse' },
    }),
  },
  {
    id: 'plante',
    label: 'Plante en pot',
    family: 'Décor & extérieur',
    icon: '🪴',
    size: [0.8, 1.4, 0.8],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('PLANTE', 'Plante verte en pot 1,4 m', 'Décor', 12, {
      brand: 'MSR',
      model: 'Kentia 140',
      unit: 'plante',
      cost: 95,
      weightKg: 18,
      specs: { Hauteur: '1,4 m', Pot: 'Zinc ou osier' },
    }),
  },
  {
    id: 'arbre',
    label: 'Arbre',
    family: 'Décor & extérieur',
    icon: '🌳',
    size: [4, 6, 4],
    resizable: true,
    defaultY: 0,
    beam: false,
    hint: 'Décor du site — non facturé',
  },
  {
    id: 'haie',
    label: 'Haie / jardinière',
    family: 'Décor & extérieur',
    icon: '🌿',
    size: [1.2, 1, 0.5],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('JARDINIERE', 'Jardinière buis artificiel 120 cm', 'Décor', 14, {
      brand: 'MSR',
      model: 'Jardinière 120',
      unit: 'module de 1,2 m',
      cost: 130,
      weightKg: 22,
      specs: { Hauteur: '1 m', Usage: 'Délimitation d’espace' },
    }),
  },
  {
    id: 'tapis',
    label: 'Tapis / allée',
    family: 'Décor & extérieur',
    icon: '🟥',
    size: [2, 0.02, 8],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('TAPIS', 'Tapis d’allée rouge — le m²', 'Décor', 4, {
      brand: 'MSR',
      model: 'Moquette événementielle',
      unit: 'm²',
      cost: 14,
      weightKg: 1,
      specs: { Classement: 'M3', Pose: 'Adhésif double face' },
    }),
  },
  {
    id: 'photobooth',
    label: 'Photobooth',
    family: 'Décor & extérieur',
    icon: '📸',
    size: [2, 2.4, 1.2],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('PHOTOBOOTH', 'Photobooth borne selfie + impressions illimitées', 'Décor', 390, {
      brand: 'Owlaris',
      model: 'Booth Studio',
      entity: 'owlaris',
      unit: 'borne',
      cost: 4200,
      weightKg: 65,
      powerW: 400,
      specs: { Impressions: 'Illimitées 10 x 15', Fond: 'Toile personnalisable', Livraison: 'Installée' },
    }),
  },
  {
    id: 'panneau',
    label: 'Panneau signalétique',
    family: 'Sécurité & signalétique',
    icon: '🪧',
    size: [1, 2, 0.1],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('PANNEAU', 'Panneau signalétique 100 x 150 cm sur pied', 'Sécurité & signalétique', 18, {
      brand: 'MSR',
      model: 'Totem Dibond',
      unit: 'panneau',
      cost: 180,
      weightKg: 14,
      specs: { Support: 'Dibond 3 mm', Impression: 'Personnalisée incluse' },
    }),
  },
  {
    id: 'palissade',
    label: 'Palissade bois',
    family: 'Décor & extérieur',
    icon: '🧱',
    size: [2, 2, 0.15],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('PALISSADE', 'Palissade bois 2 x 2 m', 'Décor', 16, {
      brand: 'MSR',
      model: 'Palissade pin',
      unit: 'panneau de 2 m',
      cost: 165,
      weightKg: 34,
      specs: { Hauteur: '2 m', Lest: 'Pied béton inclus' },
    }),
  },
  {
    id: 'fanions',
    label: 'Guirlande de fanions',
    family: 'Décor & extérieur',
    icon: '🎏',
    size: [10, 0.3, 0.05],
    resizable: true,
    defaultY: 3,
    beam: false,
    product: prod('FANIONS', 'Guirlande de fanions tissu 10 m', 'Décor', 6, {
      brand: 'MSR',
      model: 'Fanions coton',
      unit: 'guirlande de 10 m',
      cost: 45,
      weightKg: 1,
      specs: { Longueur: '10 m', Matière: 'Coton multicolore' },
    }),
  },

  /* =================================================== ÉNERGIE & TECHNIQUE */
  {
    id: 'groupe-electrogene',
    label: 'Groupe électrogène',
    family: 'Énergie & technique',
    icon: '⚡',
    size: [3.2, 1.9, 1.2],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('GE60', 'Groupe électrogène insonorisé 60 kVA', 'Énergie', 260, {
      brand: 'SDMO',
      model: 'R66',
      unit: 'groupe',
      cost: 21000,
      weightKg: 1100,
      specs: { Puissance: '60 kVA', Bruit: '62 dB à 7 m', Autonomie: '12 h', Carburant: 'Non inclus' },
    }),
  },
  {
    id: 'coffret-electrique',
    label: 'Coffret électrique',
    family: 'Énergie & technique',
    icon: '🔌',
    size: [0.6, 1.1, 0.4],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('COFFRET63', 'Coffret de distribution P17 63 A', 'Énergie', 38, {
      brand: 'Ceag',
      model: 'Coffret 63A',
      unit: 'coffret',
      cost: 720,
      weightKg: 26,
      specs: { Entrée: 'P17 63 A tri', Sorties: '2 x 32 A + 6 x 16 A', Protection: 'Différentiel 30 mA' },
    }),
  },
  {
    id: 'cable-ramp',
    label: 'Passage de câbles',
    family: 'Énergie & technique',
    icon: '➖',
    size: [1, 0.08, 0.5],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('PASSECABLE', 'Passage de câbles caoutchouc 1 m', 'Énergie', 4, {
      brand: 'Defender',
      model: 'Mid 5',
      unit: 'module de 1 m',
      cost: 85,
      weightKg: 14,
      specs: { Canaux: '5', Charge: '15 t' },
    }),
  },
  {
    id: 'rack-technique',
    label: 'Flight-case',
    family: 'Logistique & stockage',
    icon: '🧰',
    size: [1.2, 0.9, 0.7],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('FLIGHT', 'Flight-case sur roues 120 x 70 x 90 cm', 'Logistique', 16, {
      brand: 'Amptown',
      model: 'Case 1200',
      unit: 'case',
      cost: 480,
      weightKg: 38,
      specs: { Roues: '4 dont 2 freinées', Charge: '150 kg' },
    }),
  },
  {
    id: 'malle',
    label: 'Malle de rangement',
    family: 'Logistique & stockage',
    icon: '📦',
    size: [0.8, 0.6, 0.6],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('MALLE', 'Malle de rangement 80 L', 'Logistique', 4, {
      brand: 'Curver',
      model: 'Malle 80',
      unit: 'malle',
      cost: 42,
      weightKg: 6,
      specs: { Volume: '80 L', Empilable: 'Oui' },
    }),
  },
  {
    id: 'container-stockage',
    label: 'Container de stockage',
    family: 'Logistique & stockage',
    icon: '🚛',
    size: [2.44, 2.59, 6.06],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('CONTAINER20', 'Container de stockage 20 pieds', 'Logistique', 95, {
      brand: 'Divers',
      model: 'Dry 20"',
      unit: 'container',
      cost: 3200,
      weightKg: 2200,
      specs: { Volume: '33 m³', Fermeture: 'Cadenas haute sécurité', Livraison: 'Camion-grue' },
    }),
  },
  {
    id: 'remorque',
    label: 'Remorque',
    family: 'Logistique & stockage',
    icon: '🚙',
    size: [1.6, 1.6, 3.2],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('REMORQUE', 'Remorque bagagère bâchée 750 kg', 'Logistique', 45, {
      brand: 'Lider',
      model: 'Fourgon 750',
      unit: 'remorque',
      cost: 2400,
      weightKg: 280,
      specs: { PTAC: '750 kg', Volume: '5 m³', Permis: 'B' },
    }),
  },
  {
    id: 'camion',
    label: 'Camion 20 m³',
    family: 'Logistique & stockage',
    icon: '🚚',
    size: [2.4, 3.2, 7.5],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('CAMION20', 'Camion 20 m³ avec hayon — mise à disposition', 'Logistique', 185, {
      brand: 'Renault',
      model: 'Master 20 m³',
      unit: 'jour',
      cost: 42000,
      weightKg: 3500,
      specs: { Volume: '20 m³', Hayon: '750 kg', Permis: 'B (3,5 t)' },
    }),
  },
  {
    id: 'diable',
    label: 'Diable de manutention',
    family: 'Logistique & stockage',
    icon: '🛒',
    size: [0.55, 1.3, 0.6],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('DIABLE', 'Diable de manutention 300 kg', 'Logistique', 6, {
      brand: 'Fetra',
      model: 'Diable 300',
      unit: 'diable',
      cost: 180,
      weightKg: 14,
      specs: { Charge: '300 kg', Roues: 'Gonflables' },
    }),
  },
  {
    id: 'palette',
    label: 'Palette',
    family: 'Logistique & stockage',
    icon: '🟫',
    size: [1.2, 0.15, 0.8],
    resizable: false,
    defaultY: 0,
    beam: false,
  },

  /* ================================================ SÉCURITÉ & SIGNALÉTIQUE */
  {
    id: 'barrier',
    label: 'Barrière Vauban',
    family: 'Sécurité & signalétique',
    icon: '🚧',
    size: [2, 1.1, 0.5],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('VAUBAN', 'Barrière Vauban galvanisée 2 m', 'Sécurité', 3.5, {
      brand: 'Sodilor',
      model: 'Vauban 2000',
      unit: 'barrière',
      cost: 62,
      weightKg: 14,
      specs: { Longueur: '2 m', Hauteur: '1,1 m', Assemblage: 'Crochets' },
    }),
  },
  {
    id: 'barriere-mojo',
    label: 'Barrière de foule',
    family: 'Sécurité & signalétique',
    icon: '🛡️',
    size: [1.2, 1.2, 1.1],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('MOJO', 'Barrière anti-poussée type Mojo 1,2 m', 'Sécurité', 12, {
      brand: 'Mojo Barriers',
      model: 'Standard',
      unit: 'élément',
      cost: 420,
      weightKg: 32,
      specs: { Résistance: '5 kN/m', Marche: 'Podium intégré', Norme: 'EN 13200' },
    }),
  },
  {
    id: 'plot-balisage',
    label: 'Plot de balisage',
    family: 'Sécurité & signalétique',
    icon: '🔶',
    size: [0.35, 0.75, 0.35],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('PLOT', 'Cône de balisage 75 cm rétroréfléchissant', 'Sécurité', 1.5, {
      brand: 'Sodilor',
      model: 'Cône K5a',
      unit: 'cône',
      cost: 18,
      weightKg: 4,
      specs: { Hauteur: '75 cm', Bandes: 'Rétroréfléchissantes' },
    }),
  },
  {
    id: 'extincteur',
    label: 'Extincteur sur support',
    family: 'Sécurité & signalétique',
    icon: '🧯',
    size: [0.3, 1.2, 0.3],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('EXTINCTEUR', 'Extincteur 6 kg poudre + support et signalétique', 'Sécurité', 8, {
      brand: 'Sicli',
      model: 'ABC 6 kg',
      unit: 'ensemble',
      cost: 95,
      weightKg: 12,
      specs: { Classe: 'ABC', Contrôle: 'Vérification annuelle à jour' },
    }),
  },
  {
    id: 'bloc-secours',
    label: 'Bloc issue de secours',
    family: 'Sécurité & signalétique',
    icon: '🚪',
    size: [0.4, 0.2, 0.1],
    resizable: false,
    defaultY: 2.2,
    beam: false,
    product: prod('BAES', 'Bloc autonome d’éclairage de sécurité', 'Sécurité', 6, {
      brand: 'Legrand',
      model: 'BAES SATI',
      unit: 'bloc',
      cost: 68,
      weightKg: 1,
      powerW: 5,
      specs: { Autonomie: '1 h', Norme: 'NF C 71-800' },
    }),
  },

  /* ================================================ ÉCHELLE & CIRCULATION */
  /* ============================================ COMPLEMENTS GUINGUETTE 2026 */
  {
    id: 'tabouret-bar',
    label: 'Tabouret de bar',
    family: 'Mobilier & réception',
    icon: '🪑',
    size: [0.38, 0.78, 0.38],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('TABBAR', 'Tabouret de bar assise bois, piètement acier', 'Mobilier & réception', 4.5, {
      brand: 'Vondom',
      model: 'Bistrot H76',
      unit: 'tabouret',
      cost: 78,
      weightKg: 5.2,
      specs: { 'Hauteur d’assise': '76 cm', Empilable: 'Oui, par 6' },
    }),
  },
  {
    id: 'tonneau',
    label: 'Tonneau mange-debout',
    family: 'Mobilier & réception',
    icon: '🛢️',
    size: [0.72, 1.05, 0.72],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('TONNEAU', 'Tonneau chêne 225 L, plateau de service', 'Mobilier & réception', 22, {
      brand: 'MSR',
      model: 'Barrique 225',
      unit: 'tonneau',
      cost: 260,
      weightKg: 48,
      specs: { Contenance: '225 L', Essence: 'Chêne français', Plateau: 'Amovible Ø 72 cm' },
    }),
  },
  {
    id: 'botte-paille',
    label: 'Botte de paille',
    family: 'Décor & extérieur',
    icon: '🌾',
    size: [1.2, 0.5, 0.5],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('PAILLE', 'Botte de paille rectangulaire, assise ou décor', 'Décor & extérieur', 6, {
      unit: 'botte',
      cost: 12,
      weightKg: 22,
      specs: { Format: '120 x 50 x 50 cm', Reprise: 'Non — consommable' },
    }),
  },
  {
    id: 'oriflamme',
    label: 'Oriflamme',
    family: 'Décor & extérieur',
    icon: '🚩',
    size: [0.7, 3.6, 0.5],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('ORIFLAMME', 'Oriflamme voile 3,6 m sur mât fibre et socle lesté', 'Décor & extérieur', 14, {
      brand: 'Doublet',
      model: 'Goutte 360',
      unit: 'oriflamme',
      cost: 165,
      weightKg: 11,
      specs: { Hauteur: '3,6 m', Socle: 'Croix lestée 12 kg', Impression: 'Sublimation recto-verso' },
    }),
  },
  {
    id: 'urinoir',
    label: 'Urinoir collectif',
    family: 'Sanitaires & confort',
    icon: '🚻',
    size: [1.2, 1.4, 1.2],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('URINOIR4', 'Urinoir collectif 4 postes, cuve 300 L', 'Sanitaires & confort', 62, {
      brand: 'Sebach',
      model: 'Uri 4',
      unit: 'urinoir',
      cost: 980,
      weightKg: 46,
      specs: { Postes: '4', Cuve: '300 L', Autonomie: '≈ 900 passages' },
    }),
  },
  {
    id: 'cendrier',
    label: 'Cendrier sur pied',
    family: 'Sécurité & signalétique',
    icon: '🚬',
    size: [0.3, 1, 0.3],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('CENDRIER', 'Cendrier sur pied inox, socle lesté', 'Sécurité & signalétique', 5, {
      unit: 'cendrier',
      cost: 72,
      weightKg: 7,
      specs: { Hauteur: '1 m', Capacité: '4 L', Matière: 'Inox 304' },
    }),
  },
  {
    id: 'ballon-eclairant',
    label: 'Ballon éclairant',
    family: 'Lumière',
    icon: '🎈',
    size: [1.1, 4, 1.1],
    resizable: true,
    defaultY: 0,
    beam: false,
    color: '#ffe6b8',
    product: prod('BALLON', 'Ballon éclairant LED 400 W sur trépied 4 m', 'Lumière', 78, {
      brand: 'Airstar',
      model: 'Sirocco 400',
      unit: 'ballon',
      cost: 1450,
      weightKg: 24,
      powerW: 400,
      specs: { Flux: '48 000 lm', Hauteur: '4 m', Diffusion: '360°, sans éblouissement' },
    }),
  },
  {
    id: 'enrouleur',
    label: 'Enrouleur de câble',
    family: 'Énergie & technique',
    icon: '🧵',
    size: [0.6, 0.85, 0.6],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('ENROULEUR', 'Enrouleur 50 m — 3G2,5 mm² sur touret métal', 'Énergie & technique', 9, {
      brand: 'Brennenstuhl',
      model: 'Garant 50',
      unit: 'enrouleur',
      cost: 130,
      weightKg: 14,
      specs: { Longueur: '50 m', Section: '3G2,5 mm²', Protection: 'IP44, thermique' },
    }),
  },
  {
    id: 'lave-verres',
    label: 'Lave-verres',
    family: 'Bar & restauration',
    icon: '🥂',
    size: [0.47, 0.72, 0.52],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('LAVEVERRE', 'Lave-verres panier 40 x 40, cycle 120 s', 'Bar & restauration', 48, {
      brand: 'Colged',
      model: 'Steeltech 26',
      unit: 'machine',
      cost: 1250,
      weightKg: 34,
      powerW: 2800,
      specs: { Panier: '40 x 40 cm', Cycle: '120 s', Alimentation: '230 V — 2,8 kW' },
    }),
  },
  {
    id: 'fontaine-eau',
    label: 'Fontaine à eau',
    family: 'Bar & restauration',
    icon: '🚰',
    size: [0.5, 1.3, 0.45],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('FONTAINE', 'Fontaine à eau réseau, 2 becs, 60 L/h', 'Bar & restauration', 26, {
      brand: 'Eva',
      model: 'Reso 60',
      unit: 'fontaine',
      cost: 520,
      weightKg: 22,
      powerW: 350,
      specs: { Débit: '60 L/h', Becs: '2 — fraîche et tempérée', Raccord: 'Réseau 3/4"' },
    }),
  },
  {
    id: 'chariot-service',
    label: 'Chariot de service',
    family: 'Bar & restauration',
    icon: '🛒',
    size: [0.9, 0.95, 0.6],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('CHARIOT', 'Chariot inox 3 plateaux sur roulettes freinées', 'Bar & restauration', 12, {
      unit: 'chariot',
      cost: 210,
      weightKg: 18,
      specs: { Plateaux: '3', Charge: '150 kg', Roues: '4 dont 2 freinées' },
    }),
  },
  {
    id: 'benne-dechets',
    label: 'Benne à déchets',
    family: 'Logistique & stockage',
    icon: '🗑️',
    size: [1.4, 1.25, 1.1],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('BENNE', 'Conteneur roulant 770 L à couvercle', 'Logistique & stockage', 11, {
      brand: 'Sulo',
      model: 'MGB 770',
      unit: 'conteneur',
      cost: 240,
      weightKg: 48,
      specs: { Volume: '770 L', Roues: '4 pivotantes Ø 200', Couvercle: 'Plat, verrouillable' },
    }),
  },
  {
    id: 'transpalette',
    label: 'Transpalette',
    family: 'Logistique & stockage',
    icon: '🛠️',
    size: [0.55, 1.2, 1.55],
    resizable: false,
    defaultY: 0,
    beam: false,
    product: prod('TRANSPAL', 'Transpalette manuel 2,5 t, fourches 1150 mm', 'Logistique & stockage', 16, {
      brand: 'Fimm',
      model: 'BF 25',
      unit: 'transpalette',
      cost: 380,
      weightKg: 68,
      specs: { Capacité: '2 500 kg', Fourches: '1 150 x 540 mm', Levée: '85 → 200 mm' },
    }),
  },
  {
    id: 'poste-secours',
    label: 'Poste de secours',
    family: 'Sécurité & signalétique',
    icon: '⛑️',
    size: [3, 2.6, 3],
    resizable: true,
    defaultY: 0,
    beam: false,
    product: prod('PCSECOURS', 'Poste de secours — tonnelle 3 x 3 équipée et signalée', 'Sécurité & signalétique', 95, {
      unit: 'poste',
      cost: 1400,
      weightKg: 62,
      specs: { Surface: '9 m²', Équipement: 'Brancard, table, 2 chaises, éclairage', Signalétique: 'Croix blanche sur fond vert' },
    }),
  },

  {
    id: 'person',
    label: 'Personne debout',
    family: 'Échelle & circulation',
    icon: '🚶',
    size: [0.5, 1.75, 0.35],
    resizable: false,
    defaultY: 0,
    beam: false,
    hint: 'Repère d’échelle — non facturé',
  },
  {
    id: 'person-seated',
    label: 'Personne assise',
    family: 'Échelle & circulation',
    icon: '🧍',
    size: [0.5, 1.25, 0.6],
    resizable: false,
    defaultY: 0,
    beam: false,
    hint: 'Repère d’échelle — non facturé',
  },
  {
    id: 'voiture',
    label: 'Voiture',
    family: 'Échelle & circulation',
    icon: '🚗',
    size: [1.8, 1.45, 4.4],
    resizable: true,
    defaultY: 0,
    beam: false,
    hint: 'Repère d’échelle — non facturé',
  },
];

export const OBJECT_BY_ID = new Map(OBJECT_LIBRARY.map((entry) => [entry.id, entry]));

export function objectDef(id: string): ObjectDef {
  return (
    OBJECT_BY_ID.get(id) ?? {
      id,
      label: id,
      family: 'Décor & extérieur',
      icon: '📦',
      size: [1, 1, 1],
      resizable: true,
      defaultY: 0,
      beam: false,
    }
  );
}

export const OBJECT_FAMILIES = [...new Set(OBJECT_LIBRARY.map((entry) => entry.family))];

/** Identifiant du produit genere pour une reference de la bibliotheque. */
export function productIdForRef(ref: string): string {
  return `prd_${ref.toLowerCase().replace(/[^a-z0-9]+/g, '')}`;
}

/** Dimensions effectives d'un objet : cotes saisies, sinon dimensions nominales. */
export function itemSize(
  model3d: string,
  override: { width: number | null; height: number | null; depth: number | null },
): [number, number, number] {
  const def = objectDef(model3d);
  return [override.width ?? def.size[0], override.height ?? def.size[1], override.depth ?? def.size[2]];
}

/**
 * Nombre d'unites facturees pour un objet, deduit de ses cotes.
 * Un bar module se facture au metre, un mur LED a la dalle, une piste de danse
 * et un tapis au metre carre, une guirlande a la longueur.
 */
export function billableUnits(model3d: string, size: [number, number, number], qty: number): number {
  const [w, h, d] = size;
  switch (model3d) {
    case 'bar':
      return Math.max(1, Math.round(w));
    case 'led-wall':
      return Math.max(1, Math.round((w / 0.5) * (h / 0.5)));
    case 'dance-floor':
    case 'tapis':
      return Math.max(1, Math.round(w * d));
    case 'string-lights':
    case 'fanions':
      return Math.max(1, Math.round(w / 10));
    case 'truss':
      return Math.max(1, Math.round(w / 3));
    case 'stage-deck':
      return Math.max(1, Math.round((w * d) / 2));
    case 'stage-rail':
    case 'barrier':
    case 'palissade':
    case 'haie':
      return Math.max(1, Math.round(w / 2));
    case 'stage-skirt':
      return Math.max(1, Math.round(w));
    case 'cable-ramp':
      return Math.max(1, Math.round(w));
    case 'seating-block':
      return Math.max(1, Math.round(qty));
    default:
      return Math.max(1, Math.round(qty));
  }
}

/** Sols disponibles pour le terrain. */
export const GROUND_KINDS = [
  { id: 'herbe', label: 'Herbe' },
  { id: 'gazon-tondu', label: 'Gazon tondu' },
  { id: 'terre', label: 'Terre battue' },
  { id: 'sable', label: 'Sable' },
  { id: 'bitume', label: 'Bitume' },
  { id: 'beton', label: 'Béton lissé' },
  { id: 'parquet', label: 'Parquet' },
  { id: 'moquette', label: 'Moquette' },
  { id: 'carrelage', label: 'Carrelage' },
  { id: 'gravier', label: 'Gravier' },
] as const;

export type GroundKind = (typeof GROUND_KINDS)[number]['id'];
